### ISSUE TITLE
dodger endpoint problem

### ISSUE THREAD

**Issue by Celuni** [xNetcat/league-client-enhancer#1]
Hi I really appreciate the work you have put into this project and even made this open source!

I can't compile your source for some reason react is having a stroke, so I tried to recreate, made something quick in C#.

When I send a post request with json body `{"args": "%5B%5D"}` to `/lol-login/v1/session/invoke?destination=gameService&method=quitGame`
it response is an error msg:
`Couldn't assign value to 'args' of type vector because the input not a collection.`

Can you please help me out, what am I doing wrong?

**Comment by xnetcat** [comment]
try sending `{"args": "[]"}` as body.

I will fix the code soon

**Comment by xnetcat** [comment]
https://github.com/0xNetcat/league-client-enhancer/commit/adc5fc8a91dddfa0c03f492867203ab89b3fa70e fixes react compilation

**Comment by Celuni** [comment]
Thank you!
The react problem is the EOL char.

I had to manually change it for all js files even after your new fix.

I'm not really into github but I think it should be
`*.js text eol=lf`

**Comment by xnetcat** [comment]
looks fixed on my side. try recloning the whole repo

**Comment by Celuni** [comment]
I really don't want to bother you with this but I still get the same error when trying to dodge:

> Couldn't assign value to 'args' of type vector because the input not a collection.

I stripped everything away, would you mind looking over it quickly and hint me in the right direction please?
I get the same error with curl, even when I try it in C# it is the same error every time.
The problem is not the auth code or port, I use correct ones.

```
const https = require("https")
const axios = require("axios")

const agent = new https.Agent({  
  rejectUnauthorized: false
});

async function startTest() {
    var returnValue = "";
    await axios({
            method: 'POST',
            url: 'https://127.0.0.1:12345/lol-login/v1/session/invoke?destination=gameService&method=quitGame',
            data: {
                args: "%5B%5D",
            },
            headers: {
                Authorization: 'Basic aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaauth',
            },
            httpsAgent: agent,
        })
        .then((response) => {
            returnValue = response.data
        })
        .catch((error) => {
            if (error.response !== undefined) {
                returnValue = error.response.data
            }
        })
    console.log(returnValue);
}

startTest()
```

**Comment by xnetcat** [comment]
my bad, this endpoint requires data to be `x-www-form-urlencoded` not json.

here is the code:
```javascript
axios({
      method: 'POST',
      headers: {
        'content-type': 'application/x-www-form-urlencoded',
        Authorization: 'Basic aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaauth'
      },
      url: `https://127.0.0.1:12345/lol-login/v1/session/invoke?destination=gameService&method=quitGame`,
      data: 'args=%5B%5D',
      httpsAgent: agent
    })
      .then((response) => {
        console.log(response.data)
      })
      .catch((error) => {
        if (error.response !== undefined) {
          console.log(error.response.data)
        }
      })
```

**Comment by Celuni** [comment]
Wouldn't that be the same as this?
`https://127.0.0.1:12345/lol-login/v1/session/invoke?destination=gameService&method=quitGame&args=%5B%5D`

And how did you prove that this has impact because it literally does nothing to the client,
the only thing that works is DELETE on the lobby but quitGame does nothing,
and you are still stuck in champ select hidden.

Your code works only for practice tool lobby.

Did you even try it out, just queue bot intro lobby, you will hear the sound countdown timer ticking in the background you are still stuck in champ select.

The only way to dodge is by quitting the app. (Which I think is implemented by riot so if client freezes etc. you don't dodge because we know the client sucks)

What we could do is if user checks "keep me logged in" we restart the client.

`POST /process-control/v1/process/quit`

**Comment by Celuni** [comment]
If you want to test it yourself to see actual results in lobby, you can run multiple clients with league start parameter:
`--allow-multiple-clients`

Remember to set correct port/pass.

**Comment by xnetcat** [comment]
yeah, i guess you're right. i've found this endpoints when using ace-lol long time ago. i will try your suggestion later

I did not even know that it's not working in normal queues.

**Comment by Celuni** [comment]
No problem. Do you have any clue if we can sniff those api requests with wireshark, maybe we can find something that still allows us to dodge without restarting?

I've tried Telerik Fiddler but this program acts as a proxy and this won't log any traffic for localhost, if we could patch the league client to send all requests through htttps://ipv4.fiddler/endpoint instead of htttps://127.0.0.1/endpoint then we would be able to log all requests, they would be decrypted and we could see all information.

If you have reverse engineering experience it would be possible, you probably want to target libcef url parser.
I've found a write-up on this topic but I wasn't able to get any valuable information out of the url parser just some gibberish strings.
https://nickcano.com/reversing-league-of-legends-client/
This was for the old client a few years ago.

I also think that we could build a tampered libcef.dll and just replace localhost with ipv4.fiddler.

**Comment by xnetcat** [comment]
DM me on discord: netcat#2586
